name: GitHub Classroom Workflow
on: [push]
jobs:
  task07:
    runs-on: ubuntu-latest
    steps:
      - run: echo "TODO"
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd task06 && ls && make install && cd .. && cd task06-exec && ls && cd ..
      - uses: actions/upload-artifact@v2
        with:
          name: compiled
          path: task06-exec/hello
  build:
    name: Autograding
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0git remote add origin https://github.com/metametamoon/Linux-basics07.git
      - run: sudo apt install cmatrix
      - run: echo ${{ secrets.GITHUB_TOKEN }} > token.txt
      - run: ghc --version > ghc-version.txt
      - uses: ./.github/actions/task-04
        with:
          filename: "task04-result"
      - uses: actions/download-artifact@v2
        with:
          name: compiled
      - run: cd task06-exec && ls && cd ..
      - uses: education/autograding@v1
