name: GitHub Classroom Workflow
on: [push]
jobs:
  task07:
    runs-on: ubuntu-latest
    steps:
      - run: echo "TODO"
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0git remote add origin https://github.com/metametamoon/Linux-basics07.git
      - run: sudo apt install cmatrix
      - run: echo ${{ secrets.GITHUB_TOKEN }} > token.txt
      - run: ghc --version > ghc-version.txt
      - uses: actions/task04.yml
        with:
          filename: "task04-result"
      - uses: education/autograding@v1
