name: Spam
on: [push]
jobs:
  init:
    name: Create issue
    runs-on: ubuntu-latest
    steps:
      - run: ./.github/scripts/issus.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE: ${{ github.event.issue.html_url }}