name: Spam
on: [push]
jobs:
  init:
    name: Create issue
    runs-on: ubuntu-latest
    env:
      script_path: ./.github/scripts
    steps:
      - run: ${{ env.script_path }}/issus.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE: ${{ github.event.issue.html_url }}